name: AndroidBuild

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour récupérer le code source
      - name: Checkout
        uses: actions/checkout@v4.1.0

      # Étape pour installer Java 11, souvent utilisé pour les builds Android
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'  # Utilise la distribution Temurin (anciennement AdoptOpenJDK)
          java-version: '11'

      # Étape pour exécuter la compilation Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Étape pour uploader l'APK en tant qu'artefact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AndroidCICD.apk # Nom de l'artefact (APK généré)
          path: app/build/outputs/apk/debug/app-debug.apk  # Chemin vers l'APK généré
